blog/urls.py
from django.urls import path
from blog.apps import BlogConfig
from . import views

app_name = BlogConfig.name
# app_name = 'blog'

urlpatterns = [
    path("", views.BlogPostListView.as_view(), name="list"),
    path("create/", views.BlogPostCreateView.as_view(), name="create"),
    path("<int:pk>/", views.BlogPostDetailView.as_view(), name="detail"),
    path("<int:pk>/update/", views.BlogPostUpdateView.as_view(), name="update"),
    path("<int:pk>/delete/", views.BlogPostDeleteView.as_view(), name="delete"),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from .views import (
    ProductsListView,
    ProductCardView,
    ContactsView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)


app_name = CatalogConfig.name

urlpatterns = [
    path("", ProductsListView.as_view(), name="products_list"),
    path("product/<int:pk>/", ProductCardView.as_view(), name="product_card"),
    path("contacts/", ContactsView.as_view(), name="contacts"),
    path("product/create/", ProductCreateView.as_view(), name="product_create"),
    path("product/<int:pk>/update/", ProductUpdateView.as_view(), name="product_update"),
    path("product/<int:pk>/delete/", ProductDeleteView.as_view(), name="product_delete"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("catalog.urls", namespace="catalog")),
    path("blogs/", include("blog.urls", namespace="blog")),
    path("user/", include("user.urls", namespace="user")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from user.apps import UserConfig
from user.views import UserCreateView, email_verification
from user.forms import LoginForm
from . import views


app_name = UserConfig.name

urlpatterns = [
    # path('', views.user, name='user'),  # пример маршрута
    # path('login/', LoginView.as_view(template_name="login.html")),
    # path('login/', LoginView.as_view(template_name="login.html"), name='login'),
    path("login/", LoginView.as_view(authentication_form=LoginForm, template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
]

user/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUserManager(BaseUserManager):
    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)
        return self.create_user(email, password, **extra_fields)

    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        user = self.model(email=self.normalize_email(email), **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name="Email")

    avatar = models.ImageField(
        upload_to="user/avatars/", verbose_name="Аватар", blank=True, null=True, help_text="Загрузите свой аватар"
    )
    phone = models.CharField(
        max_length=35, verbose_name="Телефон", blank=True, null=True, help_text="Введите номер телефона"
    )
    country = models.CharField(max_length=50, verbose_name="Страна", blank=True, null=True, help_text="Введите страну")

    objects = CustomUserManager()  # привязываем менеджер

    token = models.CharField(max_length=100, verbose_name="Token", blank=True, null=True)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = "Пользователь"
        verbose_name_plural = "Пользователи"

    def __str__(self):
        return self.email

user/forms.py
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import BooleanField
from user.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs["class"] = "form-check-input"
            else:
                field.widget.attrs["class"] = "form-control"


class UserRegisterForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ("email", "password1", "password2")


class LoginForm(StyleFormMixin, AuthenticationForm):
    pass

user/views.py
import secrets

from django.shortcuts import get_object_or_404, redirect, reverse
from django.core.mail import send_mail

from django.urls import reverse_lazy
from django.views.generic import CreateView
from user.forms import UserRegisterForm
from user.models import User

from config.settings import EMAIL_HOST_USER


class UserCreateView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy("user:login")

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()

        host = self.request.get_host()
        url = f"http://{host}/user/email-confirm/{token}/"

        send_mail(
            subject="Подтверждение почты",
            message=f"Привет, перейди по ссылке для подтверждения почты {url}",
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email],
        )
        return super().form_valid(form)


def email_verification(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse("user:login"))


# from django.http import HttpResponse
#
#
# def user(request):
#     return HttpResponse("Привет из приложения user!")

user/templates/includes/inc_menu.html
<!-- Боковое меню -->
<div class="sidebar">
    <h5 class="mb-4">Меню</h5>
    <a href="{% url 'catalog:products_list' %}" class="active">Каталог</a>

    <a href="{% url 'catalog:contacts' %}">Контакты</a>
    <a href="{% url 'blog:list' %}">Блог</a>
    {% if user.is_authenticated %}
    <a href="{% url 'user:logout' %}">Выход</a>
    {% else %}
    <a href="{% url 'user:login' %}">Вход</a>
    {% endif %}
    <hr class="my-3">
<!--    <a href="#">Профиль</a>-->
<!--    <a href="#">Выход</a>-->
    <div class="mt-4">
<!--        <span>Пользователь</span>-->
    </div>
</div>

user/templates/includes/inc_product_data.html
{% load static %}  <!-- Эта строка обязательна! -->

<!-- Товар 1 -->
<div class="col">
    <div class="card h-100">

        <!-- Проверка наличия изображения -->
        {% if product.product_image %}
            <img src="{{ product.product_image.url }}" class="card-img-top" alt="{{ product.product_name }}">
        {% else %}
            <!-- Заглушка, если изображения нет -->
            <img src="{% static 'images/no-image.png' %}" class="card-img-top" alt="Нет изображения">
        {% endif %}

        <div class="card-body">
            <p class="card-text">Товар: {{ product.product_name }}</p>
            {% if is_product_card %}
                <p class="card-text">Описание: {{ product.product_description }}</p>
            {% else %}
                <p class="card-text">Описание: {{ product.product_description|truncatechars:100 }}</p>
            {% endif %}
            {% if is_product_card %}
                <p class="card-text">Категория: {{ product.product_category }}</p>
                <p class="card-text">Цена: {{ product.product_price }} руб.</p>
                <p class="card-text">Время создания: {{ product.created_at }}</p>
                <p class="card-text">Время обновления: {{ product.updated_at }}</p>
            {% endif %}
            <div class="d-flex justify-content-between align-items-center">
                <div class="d-flex gap-0">
                {% if is_product_card %}
                    <a class="btn btn-primary" href="{% url 'catalog:products_list' %}" role="button">Назад</a>

                    <a class="btn btn-secondary" href="{% url 'catalog:product_update' product.pk %}" role="button">Редактировать</a>
                    <a class="btn btn-secondary" href="{% url 'catalog:product_delete' product.pk %}" role="button">Удалить</a>

                {% else %}
                    <a class="btn btn-primary" href="{% url 'catalog:product_card' product.pk %}" role="button">Посмотреть</a>
                {% endif %}
                </div>

            </div>
        </div>
    </div>
</div>

user/templates/includes/inc_styles.html
body {
    background-color: #f8f9fa;
    padding-top: 20px;
}
.sidebar {
    background-color: #212529;
    color: white;
    height: 100vh;
    position: fixed;
    width: 220px;
    padding: 1rem;
}
.sidebar a {
    color: white;
    text-decoration: none;
    display: block;
    padding: 0.75rem 1rem;
    border-radius: 0.375rem;
}
.sidebar a.active {
    background-color: #0d6efd;
}
.main-content {
    margin-left: 240px; /* Отступ под сайдбар */
    padding: 0 15px;
}
.card {
    border: 1px solid #dee2e6;
    border-radius: 0.5rem;
    transition: transform 0.2s ease;
    height: 100%;
    display: flex;
    flex-direction: column;
    text-align: left;
}
.card:hover {
    transform: translateY(-5px);
    box-shadow: 0 10px 20px rgba(0, 0, 0, 0.1);
}
.card-img-top {
    height: 200px;
    object-fit: contain; /* Теперь изображение будет вписываться по длинной стороне */
}
.price {
    font-size: 1.5rem;
    color: black; /* Цвет текста — чёрный */
    margin: 0.5rem 0;
    font-weight: bold; /* Текст становится жирным */
}
.btn-buy {
    background-color: white;
    color: #0d6efd;
    border: 1px solid #0d6efd;
    padding: 0.5rem 1rem;
    border-radius: 0.375rem;
    width: 100%;
    font-weight: 500;
}
.btn-buy:hover {
    background-color: #0b5ed7;
}